version: '3.7'
services:
  minio:
    image: minio/minio
    container_name: minio_02
    hostname: minio_02
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio@dmin
    volumes:
      - /minio/data:/data
    #command: server /data
    command: server /data --console-address ":9001"
    
